### ISSUE TITLE
Passwords are stored in clear locally (no hash)

### ISSUE THREAD

**Issue by Jonarod** [graphcool/templates#151]
### Issue type:

I am submitting:

- [x ] an issue
- [ ] a feature request

After installing the Email-Password template I tried to create a new user: 

```
mutation {
  createUser(email: "jon@mail.com", password: "hello", name: "Jon") {
    id
    password
  }
}
```

The user is created and an `id` retrieved.
However, the `password` is not hashed at all: it seems to be stored in clear. 

I fact, doing:
```
query {
  allUsers {
    id
    name
    email
    password
  }
}
```
returns correct info but with a clear password (not hashed).

As a result, I am not able to `Authenticate` any users since the `bcrypt.compare(...)` actually compares the provided password with a clear password from the DB instead of an hash...

### Notes

I use `Graphcool` locally with `docker`.

**Comment by Jonarod** [comment]
Reproduced the same problem using Graphcool shared servers.
Here are the steps:

1. Create a new project:
```
graphcool init
```

2. Add email auth template:
```
graphcool-framework add-template auth/email-password
```

3. Uncomment proper lines in `types.graphql` and `graphcool.yml` 

here is my final `types.graphql`:

```
type User @model {
  id: ID! @isUnique # read-only (managed by Graphcool)

  createdAt: DateTime! # read-only (managed by Graphcool)
  updatedAt: DateTime! # read-only (managed by Graphcool)

  email: String! @isUnique
  password: String!
}
```

here is my final `graphcool.yml`

```
types: ./types.graphql

functions:
  signup:
    type: resolver
    schema: src/email-password/signup.graphql
    handler:
      code: src/email-password/signup.ts

  authenticate:
    type: resolver
    schema: src/email-password/authenticate.graphql
    handler:
      code: src/email-password/authenticate.ts

  loggedInUser:
    type: resolver
    schema: src/email-password/loggedInUser.graphql
    handler:
      code: src/email-password/loggedInUser.ts

  hello:
    handler:
      code: src/hello.js
    type: resolver
    schema: src/hello.graphql

permissions:
  - operation: "*"

```

4. Deploy project to shared servers:
```
graphcool deploy
```
I deployed to `eu-west1`

5. Go to the graphiQL console provided by the deploy command

6. Create a new user:

```
mutation {
  createUser (email: "jon@mail.com", password: "MySecretPassword") {
    id
  }
}
```

7. Check the user is created:

```
query {
  allUsers {
    id
    email
    password
  }
}
```

returns

```
{
  "data": {
    "allUsers": [
      {
        "id": "cjlr396u51c0l0138gllo608y",
        "email": "jon@mail.com",
        "password": "MySecretPassword"
      }
    ]
  }
}
```

**This is already wrong**: the value in the password field should be hashed and not displayed in clear. It should be a gibberish like: *dufeiugug78TugDHSLIKgdsjgkguk* or something like that.

8. Authenticate user:

```
mutation {
  authenticateUser (email: "jon@mail.com", password: "MySecretPassword") {
    token
  }
}
```

returns error:

```
{
  "data": {
    "authenticateUser": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "functionError": "Invalid credentials!",
      "path": [
        "authenticateUser"
      ],
      "code": 5001,
      "message": "function execution error: Invalid credentials!",
      "requestId": "eu-west-1:simple:cjlr3apz512gc01392k8afi0n"
    }
  ]
}
```

Did I miss something ?!
